-- 코드를 작성해주세요
SELECT I.ITEM_ID, I.ITEM_NAME, I.RARITY
FROM ITEM_INFO I
LEFT JOIN ITEM_TREE T ON I.ITEM_ID = T.PARENT_ITEM_ID 
WHERE PARENT_ITEM_ID IS NULL #더 이상 업그레이드할 수 없는 아이템: ITEM_ID가 PARENT_ID에 없는 ITEM
ORDER BY I.ITEM_ID DESC #아이템 ID를 기준으로 내림차순 정렬
