-- 코드를 입력하세요
SELECT AO.ANIMAL_ID,
        AO.NAME
FROM ANIMAL_OUTS AO
JOIN ANIMAL_INS AI ON AI.ANIMAL_ID = AO.ANIMAL_ID
ORDER BY (AO.DATETIME - AI.DATETIME) DESC #입양 동물 중 보호 기간이 긴 순으로 정렬
LIMIT 2 #상위 2마리 RETURN