-- 코드를 입력하세요
SELECT WAREHOUSE_ID,
    WAREHOUSE_NAME,
    ADDRESS,
    IFNULL(FREEZER_YN, 'N') AS FREEZER_YN #IF FREEZER_YN IS NULL THEN 'N'
FROM FOOD_WAREHOUSE
WHERE ADDRESS LIKE '경기도%' #Warehouse in 경기도
