-- 코드를 입력하세요
SELECT P.PRODUCT_ID, P.PRODUCT_NAME, SUM(P.PRICE*M.AMOUNT) AS TOTAL_SALES
FROM (SELECT* FROM FOOD_ORDER WHERE PRODUCE_DATE LIKE '2022-05%') M
#PRODUCE_DATE = 2022-05
LEFT JOIN FOOD_PRODUCT P ON P.PRODUCT_ID = M.PRODUCT_ID
GROUP BY P.PRODUCT_ID
ORDER BY 3 DESC, 1 #ORDER BY TOTAL_SALES DESC, PRODUCT_ID ASC