-- 코드를 입력하세요
SELECT HISTORY_ID, 
    FLOOR(DAILY_FEE * TERM * ((100 - IFNULL(DISCOUNT_RATE, 0)) / 100)) AS FEE
FROM (
    SELECT HISTORY_ID, CAR_ID, DATEDIFF(END_DATE, START_DATE) + 1 AS TERM,
    CASE WHEN DATEDIFF(END_DATE, START_DATE) + 1 >= 90 THEN '90일 이상'
        WHEN DATEDIFF(END_DATE, START_DATE) + 1 >= 30 THEN '30일 이상'
        WHEN DATEDIFF(END_DATE, START_DATE) + 1 >= 7 THEN '7일 이상' END AS DURATION
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE CAR_ID IN (
        SELECT CAR_ID FROM CAR_RENTAL_COMPANY_CAR WHERE CAR_TYPE = '트럭')) DISC
LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN DIS
ON DISC.DURATION = DIS.DURATION_TYPE AND CAR_TYPE = '트럭'
JOIN CAR_RENTAL_COMPANY_CAR RC ON RC.CAR_ID = DISC.CAR_ID
ORDER BY FEE DESC, HISTORY_ID DESC