-- 코드를 입력하세요
SELECT U.USER_ID,
    U.NICKNAME,
    SUM(DONE.PRICE) AS TOTAL_SALES
FROM (
    SELECT *
    FROM USED_GOODS_BOARD
    WHERE STATUS = 'DONE') DONE #완료된 중고 거래 인라인뷰 생성
JOIN USED_GOODS_USER U ON U.USER_ID = DONE.WRITER_ID
GROUP BY U.USER_ID
HAVING SUM(DONE.PRICE) >= 700000 #총금액이 70만 원 이상인 사람
ORDER BY TOTAL_SALES #총거래금액을 기준으로 오름차순 정렬