SELECT AO.ANIMAL_ID, 
    AO.NAME
FROM ANIMAL_INS AI
JOIN ANIMAL_OUTS AO ON AI.ANIMAL_ID = AO.ANIMAL_ID #두 테이블 JOIN
WHERE AO.DATETIME < AI.DATETIME #OUT DATE가 빠른 날짜 조건
ORDER BY AI.DATETIME #ORDER BY 조건