-- 코드를 입력하세요
SELECT DISTINCT H.CAR_ID #자동차 ID는 중복 불가
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY H
JOIN CAR_RENTAL_COMPANY_CAR C ON C.CAR_ID = H.CAR_ID
WHERE C.CAR_TYPE LIKE '세단' AND #자동차 종류가 '세단' 조건
        H.START_DATE LIKE '2022-10%' #10월에 대여를 시작한 기록 조건
ORDER BY 1 DESC #자동차 ID 기준 내림차순