-- 코드를 작성해주세요
SELECT SUM(G.SCORE) AS SCORE, E.EMP_NO, E.EMP_NAME, E.POSITION, E.EMAIL
FROM HR_EMPLOYEES E
LEFT JOIN HR_GRADE G ON G.EMP_NO = E.EMP_NO
GROUP BY E.EMP_NO
ORDER BY SCORE DESC
LIMIT 1 #Return 평가 점수가 가장 높은 사원 정보