SELECT CONCAT('/home/grep/src/', BOARD_ID, '/',FILE_ID, FILE_NAME, FILE_EXT) AS FILE_PATH #FILE_PATH 조건
FROM USED_GOODS_BOARD 
JOIN USED_GOODS_FILE USING(BOARD_ID) #SELF JOIN
WHERE VIEWS = (SELECT MAX(VIEWS) 
               FROM USED_GOODS_BOARD ) #조회수가 가장 높은 게시물 조건
ORDER BY FILE_ID DESC #ORDER BY 처리