SELECT B.CATEGORY, 
        SUM(BS.SALES) AS TOTAL_SALES
FROM BOOK B
JOIN BOOK_SALES BS ON B.BOOK_ID = BS.BOOK_ID #TABLE JOIN
WHERE SALES_DATE LIKE '2022-01%' #1월의 판매 목록만 제한
GROUP BY B.CATEGORY
ORDER BY 1 #ORDER BY 카테고리명 오름차순 조건
