-- 코드를 입력하세요
SELECT B.BOOK_ID, 
    A.AUTHOR_NAME, 
    DATE_FORMAT(B.PUBLISHED_DATE, '%Y-%m-%d') #DATE_FORMAT to remove the time
FROM BOOK B
JOIN AUTHOR A ON A.AUTHOR_ID = B.AUTHOR_ID #JOIN 2 TABLES
WHERE B.CATEGORY LIKE '경제'
ORDER BY 3 #ORDER BY PUBLISHED_DATE ASC
