-- LEFT 사용하여 조건식 만들기
SELECT CASE 
        WHEN LENGTH(PRICE) < 4 THEN 0 #천의 자리 가격대 조건
        ELSE LEFT(PRICE, 1)*10000 #만원 이상 가격대 조건
        END AS PRICE_GROUP,
        COUNT(PRODUCT_ID) AS PRODUCTS
FROM PRODUCT
GROUP BY LEFT(PRICE, 1)
ORDER BY PRICE_GROUP
